import { NollaPrng } from './nolla_prng.js';
import { BLOCKED_COLORS, GENERAL_SCENES, PIXEL_SCENE_BIOME_MAP } from './pixel_scene_config.js';
import { MATERIAL_COLOR_CONVERSION, MATERIAL_COLOR_LOOKUP, MATERIAL_WANG_COLORS } from './potion_config.js';
import { getBiomeAtWorldCoordinates } from './utils.js';
import { biomeEdgeNoiseFlag } from './wobble_flags.js';
import { loadPNG } from './png_sanitizer.js';
import { prescanPixelScene } from './poi_scanner.js';
import { BIOME_BACKGROUND_COLORS, TILE_OVERLAY_COLORS, channelDistance, makeBlackTransparent, materialDisplayColor, sceneMaterialFillColorForBiome, terrainFillColorForBiome } from './image_processing.js';
import { FILL_BIOME_MATERIALS, GENERATOR_CONFIG } from './generator_config.js';
import { appSettings } from './settings.js';
// Scenes with a per-pixel cell-color override ("visual" art): the engine's
// LoadPixelScene colors file paints each cell's color instead of the
// material's texture/flat color (the giant tree's bark, the robot eggs, the
// holy-mountain hall art). Generated by tools/gen_visual_overlays.mjs; keys
// are `${getBiomeAlias(biome)}/${sceneName}`.
import { VISUAL_OVERLAY_SCENES } from './pixel_scene_visuals.js';
// Scenes the engine draws a BACKGROUND sprite behind (LoadPixelScene's
// background_filename, z = 50): the image covers the scene's rectangle behind
// every cell, so it shows through the scene's air, through gaps its art never
// paints, and under its translucent liquids. Generated by
// tools/gen_scene_backgrounds.mjs; keys are `${getBiomeAlias(biome)}/${sceneName}`.
import { SCENE_BACKGROUNDS } from './pixel_scene_backgrounds.js';
import { SKIP_EDGE_TEXTURE_SCENES } from './pixel_scene_edge_flags.js';

// Scenes the game paints with ANOTHER scene's colors file. VISUAL_OVERLAY_SCENES
// is derived from the "<name>_visual.png sits beside <name>.png" convention, but
// the convention is not what the engine reads: LoadPixelScene's second argument
// is an explicit path, and a good number of call sites pass a sibling variant's
// art. The liquid-tank holy mountains are the visible case --
// data/scripts/biomes/temple_altar_top_shared.lua sets
// `file_visual = "data/biome_impl/temple/altar_top_visual.png"` once and passes
// it for altar_top.png AND every altar_top_<liquid>.png, so the water/blood/oil/
// radioactive/lava variants are hand-painted in game while only the plain one
// was here -- and temple_wall_ending.lua does the same for altar_top_ending.
//
// Value is the basename of the art inside the SAME data/pixel_scenes/<dir>/ as
// the scene (every one of these resolves that way, and the art already ships
// because the scene it belongs to is in VISUAL_OVERLAY_SCENES). Derived by
// scanning every LoadPixelScene call and <PixelScene colors_filename> in the
// unpacked game data for a colors file whose name is not `<material>_visual.png`,
// restricted to scenes telescope ships and confirmed by matching PNG dimensions.
//
// Two known references are deliberately absent: data/biome_impl/vault/stain.png
// and stain_ceiling.png pick one of three `stain_NN_visual.png` at random per
// instance, and telescope ships neither those decals nor their art.
const SCENE_COLORS_FILE_ALIASES = {
	"coalmine/physics_01_alt": "physics_01_visual",
	"coalmine/physics_02_alt": "physics_02_visual",
	"coalmine/shop_alt": "shop_visual",
	"coalmine/shrine01_alt": "shrine01_visual",
	"coalmine/shrine02_alt": "shrine02_visual",
	"coalmine/swarm_alt": "swarm_visual",
	"coalmine/wandtrap_h_07": "wandtrap_h_06_visual",
	"crypt/room_gate_drop_b": "room_gate_drop_visual",
	"crypt/room_liquid_funnel_b": "room_liquid_funnel_visual",
	"crypt/shop_b": "shop_visual",
	"excavationsite/machine_1_alt": "machine_1_visual",
	"excavationsite/machine_2_alt": "machine_2_visual",
	"excavationsite/machine_3b_alt": "machine_3b_visual",
	"excavationsite/machine_4_alt": "machine_4_visual",
	"excavationsite/machine_5_alt": "machine_5_visual",
	"excavationsite/machine_6_alt": "machine_6_visual",
	"excavationsite/machine_7": "machine_5_visual",
	"excavationsite/machine_7_alt": "machine_5_visual",
	"excavationsite/shop_alt": "shop_visual",
	"general/bunker2": "bunker_visual",
	"general/essenceroom_submerged": "essenceroom_visual",
	"pyramid/boss_limbs": "reward_visual",
	"snowcave/pipe_alt": "pipe_visual",
	"snowcave/verticalobservatory2_alt": "verticalobservatory2_visual",
	"snowcave/verticalobservatory_alt": "verticalobservatory_visual",
	"temple/altar_right_snowcastle": "altar_right_visual",
	"temple/altar_top_blood": "altar_top_visual",
	"temple/altar_top_ending": "altar_top_visual",
	"temple/altar_top_lava": "altar_top_visual",
	"temple/altar_top_oil": "altar_top_visual",
	"temple/altar_top_radioactive": "altar_top_visual",
	"temple/altar_top_water": "altar_top_visual",
};

/**
 * Basename (no extension) of the colors file the engine paints this scene with,
 * inside data/pixel_scenes/<dir>/, or null when the scene has none.
 */
function sceneColorsFileName(dir, name) {
	const id = `${dir}/${name}`;
	if (SCENE_COLORS_FILE_ALIASES[id]) return SCENE_COLORS_FILE_ALIASES[id];
	return VISUAL_OVERLAY_SCENES.has(id) ? `${name}_visual` : null;
}

// This was originally constant but it sometimes needs to be cleared to regenerate the cache...
export let PIXEL_SCENE_DATA = {};
export let PIXEL_SCENE_SPAWN_DATA = {}; // Populated during the prescan of pixel scenes, keyed by biome and scene name, used for looking up spawn points during generation without needing to access the image data again
// ---------------------------------------------------------------------------
// Pixel scene bitmap cache (PERF_PLAN Step 1)
//
// Each recolored variant is uploaded once as an ImageBitmap plus a mip chain
// (1/2 .. 1/16). The draw site picks a level from the camera zoom, so a zoomed-out
// frame blits a handful of pixels per scene instead of a full-resolution image, which
// is what made drawing them at low zoom expensive enough to gate off entirely.
//
// The raw recolored Uint8Array is released once its bitmap exists (the overlay worker
// recolors from the untouched base image, so any variant can be produced again). Entries
// are evicted least-recently-drawn first over a byte budget; an evicted variant is
// re-requested from the overlay worker through the rebuild hook below.
// ---------------------------------------------------------------------------
export const PIXEL_SCENE_MAX_MIP = 4; // 1/2, 1/4, 1/8, 1/16
const PIXEL_SCENE_BITMAP_CACHE = new Map(); // `${key}/${variantKey}` -> entry
let pixelSceneCacheBytes = 0;
let pixelSceneDrawTick = 0;

// Left in place of a released Uint8Array so the "do we already have this variant?" checks
// in overlay_manager / world_manager don't re-request it while its bitmap is still alive.
const VARIANT_RELEASED = { released: true };

// ---------------------------------------------------------------------------
// Bitmaps are BUILT IN THE OVERLAY WORKER, never on this thread.
//
// Turning a scene's pixels into a drawable used to happen synchronously on the
// first draw that needed it: recolor -> visual-art overlay -> putImageData ->
// transferToImageBitmap, then a GPU readback + JS halving for every mip level,
// and for a textured instance a full per-pixel material build on top. That was
// 30-110 ms for one large scene scrolling into view and a 50 ms frame at the
// overview zoom -- the worst frames the renderer had once the tooltip readback
// was gone. Now a cache miss posts a BUILD_SCENE_BITMAPS request (through the
// hook overlay_manager registers below) and returns nothing to draw; the worker
// answers with the finished ImageBitmap chain, which lands here through
// putPixelSceneBitmaps(). The scene is missing for the frames in between, which
// drawNow hides by warming scenes in a margin around the view before they are
// visible (warmPixelScene).
//
// A textured instance that is still being built draws its FLAT variant meanwhile
// (same key without the position), so crossing the texture zoom shows a flat
// scene that sharpens rather than a hole.
// ---------------------------------------------------------------------------
let sceneBitmapRequester = null;   // (request, sceneData) => void, set by overlay_manager
const pendingSceneBitmaps = new Map();   // cacheKey -> textured (in flight at the worker)
// Bumped whenever the cache is cleared, so a reply for the old contents is dropped.
let sceneBitmapEpoch = 0;
// In-flight caps. The worker is FIFO and cannot cancel: with no cap a pan at the
// textured zoom would queue every instance it passed over (each a 30-110 ms
// build) ahead of the ones actually on screen. Misses past the cap are simply
// asked again on the next draw, which is what keeps requests tracking the view.
const MAX_INFLIGHT_TEXTURED = 6;
const MAX_INFLIGHT_FLAT = 48;

export function setPixelSceneBitmapRequester(fn) {
	sceneBitmapRequester = fn;
}

/** Scene bitmaps asked of the worker and not back yet (the harness waits on it). */
export function pendingPixelSceneBitmaps() {
	return pendingSceneBitmaps.size;
}

function requestSceneBitmaps(pixelScene, cacheKey, textured) {
	if (!sceneBitmapRequester || pendingSceneBitmaps.has(cacheKey)) return;
	const data = PIXEL_SCENE_DATA[pixelScene.key];
	if (!data) return;
	let inflight = 0;
	for (const t of pendingSceneBitmaps.values()) if (t === textured) inflight++;
	// Render Everything asks for a textured build of every visible instance at
	// any zoom (~1150 at the overview); at the normal cap that trickles in over
	// a minute, so let the worker run flat out there. Its whole point is a
	// zoom-independent frame, not a responsive one.
	const texturedCap = appSettings.renderEverything ? 32 : MAX_INFLIGHT_TEXTURED;
	if (inflight >= (textured ? texturedCap : MAX_INFLIGHT_FLAT)) return;
	pendingSceneBitmaps.set(cacheKey, textured);
	sceneBitmapRequester({
		cmd: 'BUILD_SCENE_BITMAPS',
		epoch: sceneBitmapEpoch,
		cacheKey,
		key: pixelScene.key,
		variantKey: pixelScene.variantKey || '',
		x: pixelScene.x,
		y: pixelScene.y,
		textured,
		maxLevel: sceneMaxMipLevel(data.width, data.height),
	}, data);
}

/**
 * Accepts a finished bitmap chain from the worker (overlay_manager routes the
 * SCENE_BITMAPS reply here). Returns true when something new is drawable.
 */
// Bumped whenever a drawable scene appears or disappears, so a caller that
// composites many scenes into one bitmap (app.js sceneBake) knows to rebuild.
let sceneBitmapVersion = 0;
export function pixelSceneBitmapVersion() {
	return sceneBitmapVersion;
}

export function putPixelSceneBitmaps(msg) {
	pendingSceneBitmaps.delete(msg.cacheKey);
	sceneBitmapVersion++;
	const bitmaps = [...(msg.levels || []), msg.airMask].filter(Boolean);
	if (msg.epoch !== sceneBitmapEpoch || !msg.levels || !msg.levels[0]) {
		for (const b of bitmaps) b.close?.();
		return false;
	}
	const old = PIXEL_SCENE_BITMAP_CACHE.get(msg.cacheKey);
	if (old) releasePixelSceneEntry(old);
	const entry = {
		cacheKey: msg.cacheKey,
		width: msg.width,
		height: msg.height,
		levels: new Array(PIXEL_SCENE_MAX_MIP + 1).fill(null),
		maxLevel: msg.levels.length - 1,
		airMask: msg.airMask || null,
		bytes: 0,
		used: 0,
	};
	for (let l = 0; l < msg.levels.length; l++) addPixelSceneBitmap(entry, l, msg.levels[l]);
	if (entry.airMask) {
		const bytes = entry.airMask.width * entry.airMask.height * 4;
		entry.bytes += bytes;
		pixelSceneCacheBytes += bytes;
	}
	PIXEL_SCENE_BITMAP_CACHE.set(entry.cacheKey, entry);
	// The bitmap is now the only copy this thread needs of a biome-recolored
	// variant: material lookups (utils.js) read the pre-biome variants, which are
	// left alone, and the worker rebuilds any variant from the base image.
	const data = PIXEL_SCENE_DATA[msg.key];
	if (!msg.textured && data?.variants && msg.variantKey.includes('biome=')
		&& ArrayBuffer.isView(data.variants[msg.variantKey])) {
		data.variants[msg.variantKey] = VARIANT_RELEASED;
	}
	return true;
}

/** Halving stops once either axis would round to nothing. */
export function sceneMaxMipLevel(width, height) {
	return Math.min(PIXEL_SCENE_MAX_MIP, Math.floor(Math.log2(Math.max(1, Math.min(width, height)))));
}

export function getPixelSceneCacheStats() {
	return { entries: PIXEL_SCENE_BITMAP_CACHE.size, bytes: pixelSceneCacheBytes, pending: pendingSceneBitmaps.size };
}

function releasePixelSceneEntry(entry) {
	for (const bitmap of entry.levels) {
		if (bitmap) bitmap.close();
	}
	if (entry.airMask) entry.airMask.close();
	pixelSceneCacheBytes -= entry.bytes;
	PIXEL_SCENE_BITMAP_CACHE.delete(entry.cacheKey);
	// No version bump: a bake that already holds the evicted scene's pixels
	// stays correct, and bumping here made every eviction a full rebuild.
}

export function clearPixelSceneBitmapCache() {
	for (const entry of [...PIXEL_SCENE_BITMAP_CACHE.values()]) releasePixelSceneEntry(entry);
	pixelSceneCacheBytes = 0;
	pendingSceneBitmaps.clear();
	sceneBitmapEpoch++;
	sceneBitmapVersion++;
}

function evictPixelSceneBitmaps(keep) {
	// Under Render Everything the full-res textured instances of a whole
	// overview view (~270 MB, more at 4K) do not fit the default budget, and
	// evicting them only re-requests them next frame: the cache would thrash
	// and never converge. Give the debug mode room instead.
	const budgetMB = appSettings.renderEverything
		? Math.max(appSettings.pixelSceneBitmapBudgetMB || 256, 2048) : (appSettings.pixelSceneBitmapBudgetMB || 256);
	const budget = budgetMB * 1024 * 1024;
	if (pixelSceneCacheBytes <= budget) return;
	const entries = [...PIXEL_SCENE_BITMAP_CACHE.values()].sort((a, b) => a.used - b.used);
	for (const entry of entries) {
		if (pixelSceneCacheBytes <= budget) break;
		if (entry === keep) continue; // never drop the one we are about to draw
		releasePixelSceneEntry(entry);
	}
}

function addPixelSceneBitmap(entry, level, bitmap) {
	const bytes = bitmap.width * bitmap.height * 4;
	entry.levels[level] = bitmap;
	entry.bytes += bytes;
	pixelSceneCacheBytes += bytes;
}

export function bitmapFromPixels(width, height, pixels) {
	const canvas = new OffscreenCanvas(width, height);
	const ctx = canvas.getContext('2d');
	const imageData = ctx.createImageData(width, height);
	imageData.data.set(pixels);
	ctx.putImageData(imageData, 0, 0);
	return canvas.transferToImageBitmap();
}

/**
 * The engine-faithful pixels for one stamped scene instance, or null when the
 * atlas/band tables are not loaded (or scene texturing is off).
 *
 * Runs the variant key the same way the overlay worker does -- material
 * substitutions first, in wang color space, so the texturing step still sees wang
 * colors -- but from the untouched base image and with the instance's own world
 * position, which is what the texture sampling needs.
 */
export function buildTexturedScenePixels(pixelScene, pixelSceneData, ignoreSettings = false) {
	// The worker builds on the main thread's say-so (it decided `textured` from
	// its own settings); its copy of the settings can lag a SYNC behind.
	if (!(ignoreSettings ? sceneTextureModules?.atlas.getMaterialAtlas() : sceneTextureAtlas())) return null;
	let pixels = pixelSceneData.imgElement;
	let biome = 'general';
	for (const part of (pixelScene.variantKey || '').split('&')) {
		const eq = part.indexOf('=');
		if (eq < 0) continue;
		if (part.slice(0, eq) === 'biome') biome = part.slice(eq + 1);
		else pixels = recolorPixelScene(pixels, parseInt(part.slice(0, eq), 16), parseInt(part.slice(eq + 1), 16));
	}
	return texturePixelSceneForBiome(pixelSceneData.name, pixels, pixelSceneData.width, pixelSceneData.height,
		biome, pixelScene.x, pixelScene.y);
}

// Source-over blend of a scene's visual-art override onto a COPY of its built
// pixels, restricted to opaque (painted-cell) destination pixels. The visual may
// be smaller than the scene (hall_b/hall_br); both are anchored top-left.
export function overlayVisualArt(raw, width, height, art) {
	const out = new Uint8Array(raw.length);
	out.set(raw);
	const w = Math.min(width, art.width), h = Math.min(height, art.height);
	const s = art.data;
	for (let y = 0; y < h; y++) {
		for (let x = 0; x < w; x++) {
			const si = (y * art.width + x) * 4;
			const a = s[si + 3];
			if (a === 0) continue;
			const di = (y * width + x) * 4;
			if (out[di + 3] !== 255) continue; // no cell here, art places none either
			if (a === 255) {
				out[di] = s[si]; out[di + 1] = s[si + 1]; out[di + 2] = s[si + 2];
			} else {
				const inv = 255 - a;
				out[di] = (s[si] * a + out[di] * inv + 127) / 255 | 0;
				out[di + 1] = (s[si + 1] * a + out[di + 1] * inv + 127) / 255 | 0;
				out[di + 2] = (s[si + 2] * a + out[di + 2] * inv + 127) / 255 | 0;
			}
		}
	}
	return out;
}

// Halve an image the way a cutout sprite wants to be halved: point sampling, but never
// losing coverage.
//
// Scene alpha is binary - a pixel is either painted material or air - and the seam
// between a scene and whatever it sits on is often one pixel thin. Averaging the 2x2
// block (a box filter) turns that seam into partial alpha, so the dark world behind
// shows through as a hairline crack along the scene edge; plain point sampling drops the
// seam outright and opens the same crack, wider. So the output takes the point sample
// (the block's lower-right pixel, which is what a nearest-neighbour downscale picks) and
// falls back to whichever of the other three is painted when that one is air. Painted
// area can only grow, never perforate, and alpha stays binary all the way down.
export function halveWithoutHoles(img) {
	const sw = img.width, sh = img.height, s = img.data;
	// Round up, so an odd-sized level keeps its last row/column instead of dropping it -
	// that trailing row is exactly the kind of one-pixel edge this reduction exists to keep.
	const w = Math.max(1, Math.ceil(sw / 2)), h = Math.max(1, Math.ceil(sh / 2));
	const out = new ImageData(w, h);
	const d = out.data;
	for (let y = 0; y < h; y++) {
		const rowLo = Math.min(y * 2 + 1, sh - 1) * sw;
		const rowHi = y * 2 * sw;
		for (let x = 0; x < w; x++) {
			const colLo = Math.min(x * 2 + 1, sw - 1);
			const colHi = x * 2;
			let p = (rowLo + colLo) * 4;
			if (s[p + 3] !== 255) {
				const b = (rowLo + colHi) * 4, c = (rowHi + colLo) * 4, e = (rowHi + colHi) * 4;
				if (s[b + 3] > s[p + 3]) p = b;
				if (s[c + 3] > s[p + 3]) p = c;
				if (s[e + 3] > s[p + 3]) p = e;
			}
			const o = (y * w + x) * 4;
			d[o] = s[p]; d[o + 1] = s[p + 1]; d[o + 2] = s[p + 2]; d[o + 3] = s[p + 3];
		}
	}
	return out;
}

// Largest mip whose resolution still meets the on-screen resolution: at camera zoom z one
// world pixel covers z screen pixels, so a 1/2^L bitmap is enough while 2^-L >= z.
// Anything at or above 1:1 draws the native image, exactly as before.
export function pixelSceneMipLevel(z) {
	if (!(z > 0) || z >= 1) return 0;
	const level = Math.floor(Math.log2(1 / z));
	return level > PIXEL_SCENE_MAX_MIP ? PIXEL_SCENE_MAX_MIP : level;
}

export function injectPixelSceneSpawnData(cachedData) {
	PIXEL_SCENE_SPAWN_DATA = cachedData;
}

export function injectPixelSceneData(cachedData) {
    PIXEL_SCENE_DATA = cachedData;
}

// How close a biome's background color may sit to its fill color before air
// painted with it would be indistinguishable from the surrounding solid rock,
// and how far to darken the fill when that happens.
const AIR_OVER_FILL_TOLERANCE = 24;
const AIR_OVER_FILL_DARKEN = 0.45;

const SCENES_TO_NOT_RECOLOR = ["wand_altar", "wand_altar_vault", "potion_altar", "potion_altar_vault"]; // It would be a waste to recolor these for every biome
const PIXEL_SCENE_AIR_TRANSPARENCY_EXCEPTIONS = {
	"the_end_shop": 0xff,
	"cavern": 0xff,
	"friendroom": 0xff,
	"eyespot": 0xff,
	"altar_snowcastle_capsule": 0xff,
	"altar_vault_capsule": 0xff,
	"altar_snowcave_capsule": 0xff,
	// These two look good when solid if there isn't custom art, but bad if there is. Not really sure what the best option is
	//"altar_top": 0xff,
	//"altar_top_ending": 0xff,
	"tower_start": 0xff,
	"solid_wall_hidden_cavern": 0xff,
	"watercave_layout_1": 0xff,
	"watercave_layout_2": 0xff,
	"watercave_layout_3": 0xff,
	"watercave_layout_4": 0xff,
	"watercave_layout_5": 0xff,
	// Otherwise assume transparent?
}

export async function reloadPixelSceneCache() {
	clearPixelSceneBitmapCache();
	PIXEL_SCENE_DATA = {};
	await loadPixelSceneData();
}

// Returns the bitmap to draw for this scene at the requested mip level (0 = native), or
// null when its recolored pixels aren't available yet. The caller always draws it into
// the scene's full-resolution world rectangle, so the level only changes sampling.
function pixelSceneEntry(pixelScene, level = 0, warmOnly = false) {
	// With material textures on, a scene's pixels come from its material textures
	// sampled at ABSOLUTE world coordinates, so two instances of the same variant
	// no longer look alike: the cache key has to carry the instance's position.
	//
	// Only at mip level 0 though (zoom > 0.5, the same threshold as the GL
	// terrain's MATERIAL_DETAIL_MIN_ZOOM): a textured instance is a full-res
	// per-pixel CPU build, and zoomed out every visible instance would pay it
	// just to be sampled down to 1/16. Below the threshold scenes share the flat
	// variant cache, matching the terrain's own flat falloff.
	const textured = level === 0 && !!sceneTextureAtlas();
	const variantKey = pixelScene.variantKey || '';
	const flatKey = `${pixelScene.key}/${variantKey}`;
	const cacheKey = textured ? `${flatKey}@${pixelScene.x},${pixelScene.y}` : flatKey;
	const entry = PIXEL_SCENE_BITMAP_CACHE.get(cacheKey);
	if (entry) return entry;
	if (!warmOnly || !textured) requestSceneBitmaps(pixelScene, cacheKey, textured);
	if (!textured) return null;
	// Flat stand-in while the textured instance is being built (or, when only
	// warming, the flat variant is all that is asked for: the textured build is
	// per instance and expensive, so it waits until the instance is on screen).
	const flat = PIXEL_SCENE_BITMAP_CACHE.get(flatKey);
	if (flat) return flat;
	requestSceneBitmaps(pixelScene, flatKey, false);
	return null;
}

/**
 * Asks the worker for a scene's bitmaps without drawing it, so a scene about to
 * scroll into view is ready when it does. Textured instances are not warmed.
 */
export function warmPixelScene(pixelScene, level = 0) {
	pixelSceneEntry(pixelScene, level, true);
}

export function getPixelSceneCanvas(pixelScene, level = 0) {
	const entry = pixelSceneEntry(pixelScene, level);
	if (!entry) return null;
	entry.used = ++pixelSceneDrawTick;
	const wanted = level > entry.maxLevel ? entry.maxLevel : level;
	const bitmap = entry.levels[wanted];
	evictPixelSceneBitmaps(entry);
	return bitmap;
}

/**
 * The scene's FORCE AIR mask, to be drawn with `destination-out` before the
 * scene itself, or null when it has none.
 *
 * Air in a scene PNG (#000042) is not a color the game paints, it is an
 * instruction to erase whatever terrain the chunk generated there. Only the
 * textured build carries the mask: with textures off the flat recolor keeps its
 * old "paint the background color opaque over a fill biome" approximation, so
 * that path renders exactly as before.
 *
 * Cheap to call right after getPixelSceneCanvas() -- pass the same level so it
 * hits the same cache entry (flat zoomed-out entries carry no mask).
 */
export function getPixelSceneAirMask(pixelScene, level = 0) {
	return pixelSceneEntry(pixelScene, level)?.airMask ?? null;
}

function getBiomeAlias(biomeName) {
	// Aliases to avoid needing to duplicate files for repeated biomes
	if (biomeName === "coalmine_alt") return "coalmine";
	if (biomeName === "excavationsite_cube_chamber") return "excavationsite";
	if (biomeName === "snowcave_secret_chamber") return "snowcave";
	if (biomeName === "sandcave" || biomeName === "snowcastle_cavern" || biomeName === "snowcastle_hourglass_chamber") return "snowcastle";
	if (biomeName === "rainforest_open" || biomeName === "rainforest_dark") return "rainforest";
	if (biomeName === "vault_frozen") return "vault";
	if (biomeName === "the_end" || biomeName === "the_sky") return "crypt";
	if (biomeName === "scale") return "overworld";
	if (biomeName.includes("temple")) return "temple";
	if (biomeName.includes("pyramid")) return "pyramid";
	if (biomeName.includes("mountain")) return "mountain";
	return biomeName;
}

function getPixelSceneVariant(pixelSceneKey, variantKey) {
	if (variantKey === '') return PIXEL_SCENE_DATA[pixelSceneKey].imgElement;
	if (PIXEL_SCENE_DATA[pixelSceneKey].variants[variantKey]) return PIXEL_SCENE_DATA[pixelSceneKey].variants[variantKey];
	console.log(`No variant found for pixel scene key ${pixelSceneKey} with variant key ${variantKey}?`);
	return null;
}

//const GENERAL_SCENES = ["wand_altar", "wand_altar_vault", "potion_altar", "potion_altar_vault"]; // These scenes are used in multiple biomes, so we can check for them first before doing the biome-specific lookup
const GENERAL_SCENE_NAMES = GENERAL_SCENES["extras"].map(scene => scene.name);

// Don't use the alias here because spawn points can have different indices per "duplicate" biome, so we need to keep them separate in the data
function getPixelSceneKey(biomeName, sceneName) {
	if (biomeName.includes("temple")) return "temple/" + sceneName;
	if (biomeName.includes("pyramid")) return "pyramid/" + sceneName;
	if (biomeName.includes("mountain")) return "mountain/" + sceneName;
	if (!biomeName || GENERAL_SCENE_NAMES.includes(sceneName) || !GENERATOR_CONFIG[biomeName]) return "general/" + sceneName;
	return biomeName + "/" + sceneName;
}

export async function loadPixelSceneData() {
	// The material atlas + band tables the textured build needs. Started here (main
	// thread, once, well before the first draw) rather than on demand, so the draw
	// path can stay synchronous and simply fall back to flat colors until it lands.
	initPixelSceneTextures();
	// Load key value pairs for all pixel scenes
	let loaded = 0;
	for (const biome of Object.keys(PIXEL_SCENE_BIOME_MAP)) {
		const biomeScenes = PIXEL_SCENE_BIOME_MAP[biome];
		for (const sceneList of Object.values(biomeScenes)) {
			for (const scene of sceneList) {
				if (scene.name === "") continue; // Skip the "no scene" option
				const key = getPixelSceneKey(biome, scene.name);
				if (!PIXEL_SCENE_DATA[key]) {
					// `dir` overrides the folder for the entries whose PNG does not
					// live under their own biome's name: the pyramid's interior rooms
					// are data/biome_impl/crypt/*.png (PYRAMID_SCENES). The KEY still
					// comes from the biome, because a spawn color's index is
					// per-biome, so the two biomes' copies stay separate records.
					const alias = scene.dir ?? getBiomeAlias(biome);
					const url = `../data/pixel_scenes/${alias}/${scene.name}.png`;
					const imgData = await loadPNG(url);
					makeBlackTransparent(imgData.data);
					// The cell-color override art, kept as-is (its black pixels are
					// real art, so no makeBlackTransparent here). A failed fetch just
					// means this scene renders material-derived, like any other.
					let visualArt = null;
					let artMask = null;
					const artName = sceneColorsFileName(alias, scene.name);
					if (artName) {
						try {
							const vis = await loadPNG(`../data/pixel_scenes/${alias}/${artName}.png`);
							visualArt = { data: vis.data, width: vis.width, height: vis.height };
							// Bit-packed "art covers this scene pixel" mask, for the hover
							// readout's "Art:" line (app.js pushOriginLines) -- small enough
							// to clone into the overlay worker, unlike the art itself.
							// It plays NO part in the edge-decal pass: the art overrides
							// cell colors only, never materials, so edges are decided from
							// the material grid alone.
							artMask = new Uint8Array((imgData.width * imgData.height + 7) >> 3);
							const aw = Math.min(imgData.width, vis.width), ah = Math.min(imgData.height, vis.height);
							for (let y = 0; y < ah; y++) {
								for (let x = 0; x < aw; x++) {
									if (vis.data[(y * vis.width + x) * 4 + 3] >= 128) {
										const p = y * imgData.width + x;
										artMask[p >> 3] |= 0x80 >> (p & 7);
									}
								}
							}
						} catch (err) {
							console.warn(`visual art ${artName}.png missing for ${alias}/${scene.name}:`, err);
						}
					}
					// Prescan the pixel scene for spawn points and store them in a global lookup for later use during generation, keyed by biome and scene name
					const spawnPoints = prescanPixelScene(imgData, biome);
					PIXEL_SCENE_SPAWN_DATA[key] = spawnPoints;
					//console.log(`Loaded pixel scene ${key} with ${spawnPoints.length} spawn points.`);
					PIXEL_SCENE_DATA[key] = {
						key: key,
						biome: biome,
						name: scene.name,
						dir: alias, // data/pixel_scenes/<dir>/<name>.png -- the key can differ (getPixelSceneKey)
						imgElement: imgData.data, // Store the image data directly since we need to manipulate it for recoloring
						width: imgData.width,
						height: imgData.height,
						//spawnPoints: spawnPoints,
						isCosmetic: spawnPoints.length === 0, // If there are no spawn points, we can consider it purely cosmetic and can optionally skip some checks during generation
						// Which recolor classes this scene actually contains, so it only
						// pays for a per-chunk variant when one of them depends on the
						// chunk it lands in (underlyingBiomeSuffix).
						...classifyPixelSceneColors(imgData.data),
						// The game's `skip_edge_textures`: this scene's cells still erase
						// the terrain decal pass under them, but the scene runs no decal
						// pass of its own (js/pixel_scene_edge_flags.js).
						skipEdgeTextures: SKIP_EDGE_TEXTURE_SCENES.has(`${alias}/${scene.name}`),
						visualArt, // per-pixel cell-color override art, or null
						// Basename of the colors file that art came from, for the hover
						// readout -- not always `${name}_visual` (SCENE_COLORS_FILE_ALIASES).
						artName,
						artMask, // bit-packed art coverage (MSB-first), or null
						// Repo-relative path of this scene's background sprite, or null.
						// Just a string: the bitmap itself is owned by the background
						// layer (js/biome_backgrounds.js), which draws it, so nothing
						// large is cloned into the overlay worker with this record.
						backgroundArt: SCENE_BACKGROUNDS[`${alias}/${scene.name}`] ?? null,
						variants: {}, // Used for color material changes, keyed as `${color}=${material}`
					};
					loaded++;
				}
			}
		}
	}
	console.log(`Loaded ${loaded} pixel scenes.`);
}

// This function scans the pixel scene image for blocked room colors, and returns an array of room objects with their coordinates and colors
export function blockOutRooms(pixels, width, height) {
	let rooms = [];
	for (let y = 4; y < height; y++) {
		for (let x = 0; x < width; x++) {
			const idx = (y * width + x) * 3;
			const color = (pixels[idx] << 16) | (pixels[idx+1] << 8) | pixels[idx+2];
			if (color === 0x000000 || color === 0xffffff) continue;
			if (!BLOCKED_COLORS.includes(color)) continue;

			let startX = x+1;
			let startY = y+1;
			let endX = x+1;
			let endY = y+1;
			let foundEnd = false;
			while (!foundEnd && endX < width) {
				if (endX >= width) break;
				const tempIdx = (startY * width + endX) * 3;
				const tempColor = (pixels[tempIdx] << 16) | (pixels[tempIdx+1] << 8) | pixels[tempIdx+2];
				if (tempColor === 0x000000 || tempColor === 0x323232) {
					endX++;
					continue;
				}
				endX--;
				foundEnd = true;
			}
			if (endX >= width) endX = width - 1;
			foundEnd = false;
			while (!foundEnd && endY < height) {
				if (endY >= height) break;
				const tempIdx = (endY * width + startX) * 3;
				const tempColor = (pixels[tempIdx] << 16) | (pixels[tempIdx+1] << 8) | pixels[tempIdx+2];
				if (tempColor === 0x000000 || tempColor === 0x323232) {
					endY++;
					continue;
				}
				endY--;
				foundEnd = true;
			}
			if (endY >= height) endY = height - 1;

			if (endX > startX && endY > startY) {
				//console.log(`Blocking out room from (${startX}, ${startY}) to (${endX}, ${endY})`);

				// Block out the room with pixels to block pathfinding
				for (let by = startY; by <= endY; by++) {
					for (let bx = startX; bx <= endX; bx++) {
						const bIdx = (by * width + bx) * 3;
						// Magenta for debug
						pixels[bIdx] = 0xff;
						pixels[bIdx + 1] = 0x01;
						pixels[bIdx + 2] = 0xff;
					}
				}
			}

			rooms.push({color, startX, startY, endX, endY});
		}
	}
	return rooms;
}

const CHECK_PIXEL_SCENE_BIOME = true;

// Trailer altar example for validating that the bounds check is working correctly:
// Seed: 119164939, NG+1
// Appears in PW 0, disappears in PW -1, second one appears in PW 9

// TODO: Refactoring pixel scenes to not do the image manipulation here at all
// Instead do it in the overlay worker when generating for display
// Minimize the amount of information returned to keep the worker messages lightweight

export function loadPixelScene(biomeData, biomeName, sceneName, ws, ng, x, y, skipCosmeticScenes = true, checkBounds = true, gameMode = 'normal') {
	const pixelSceneKey = getPixelSceneKey(biomeName, sceneName);
	if (!PIXEL_SCENE_DATA[pixelSceneKey]) {
		console.warn(`Pixel scene data not found for key ${pixelSceneKey}. This should not happen because we preload all pixel scene images.`);
		return null;
	}
	const pixelSceneData = PIXEL_SCENE_DATA[pixelSceneKey];
	if (pixelSceneData.isCosmetic && skipCosmeticScenes) {
		// If the scene is purely cosmetic and we're skipping cosmetic scenes, skip it
		return null;
	}
	// checkBounds matches the skip_biome_checks parameter and only checks the top-left corner, while randomly placed pixel scenes check all corners
	if (checkBounds && biomeName && CHECK_PIXEL_SCENE_BIOME) {
		const topLeft = getBiomeAtWorldCoordinates(biomeData, x, y, ng > 0, gameMode);
		// Check wobbled biome based on edge noise
		if (!topLeft.biome && biomeEdgeNoiseFlag(topLeft.colorInt, 'noise_biome_edges') === null) {
			// This does not appear to ever trigger?
			console.log(`Rejected spawn for pixel scene ${sceneName} at (${x}, ${y}) with unknown biome color ${topLeft.colorInt.toString(16)} in original biome ${biomeName}. This likely means the biome map is missing colors from the data.wak unpack, such as NG+ palette swaps. Accepting spawn but returning null biome so it can be recolored without a biome-specific variant.`);
			return null;
		}
		// Unsure about this, but it would make sense... Seems to help
		if (topLeft.biome !== biomeName) {
			//console.log(`Rejected spawn for pixel scene ${sceneName} at (${x}, ${y}) in biome ${biomeName} because top-left corner is in biome ${topLeft.biome}.`);
			return null;
		}
	}
	// Recolor the pixel scene for the biome if needed
	if (!biomeName || biomeName === "general") {
		// Better fallback
		if (SCENES_TO_NOT_RECOLOR.includes(sceneName)) {
			biomeName = "general";
		} else {
			biomeName = getBiomeAtWorldCoordinates(biomeData, x + pixelSceneData.width/2, y + pixelSceneData.height/2, ng > 0, gameMode, true)?.biome || "general";
		}
	}
	// Exception to the exception because it's in two different biomes which need to be recolored differently
	// There are a few other pixel scenes which could follow this pattern, but they're drawn in the custom art already
	if (sceneName !== "the_end_shop" && GENERAL_SCENE_NAMES.includes(sceneName)) {
		biomeName = "general";
	}
	// Alternative?
	/*
	if (SCENES_TO_NOT_RECOLOR.includes(sceneName)) {
		biomeName = "general";
	}
	else if (!biomeName || biomeName === "general") {
		biomeName = getBiomeAtWorldCoordinates(biomeData, x + pixelSceneData.width/2, y + pixelSceneData.height/2, ng > 0, gameMode)?.biome || "general";
	}
	*/
	const variantKey = `biome=${biomeName}${underlyingBiomeSuffix(biomeData, pixelSceneData, biomeName, sceneName, x, y, ng, gameMode)}`;
	/*
	if (!PIXEL_SCENE_DATA[pixelSceneKey].variants[variantKey]) {
		PIXEL_SCENE_DATA[pixelSceneKey].variants[variantKey] = recolorPixelSceneForBiome(sceneName, getPixelSceneVariant(pixelSceneKey, ''), PIXEL_SCENE_DATA[pixelSceneKey].width, PIXEL_SCENE_DATA[pixelSceneKey].height, biomeName, x, y);
		//console.log(`Created biome variant of pixel scene ${pixelSceneKey} with key ${variantKey}`);
	}
	*/
	//const pixelSceneImage = PIXEL_SCENE_DATA[pixelSceneKey].variants[variantKey];
	//console.log(`Loaded pixel scene ${sceneName} for biome ${biomeName} at (${x}, ${y}) with keys ${pixelSceneKey} / ${variantKey}`);
	return {
		key: pixelSceneKey,
		variantKey: variantKey,
		name: sceneName,
		//imgElement: pixelSceneImage,
		width: pixelSceneData.width,
		height: pixelSceneData.height,
		x: x,
		y: y,
		//spawnPoints: pixelSceneData.spawnPoints,
		material: null,
		type: 'pixel_scene'
	};
}

export function loadRandomPixelScene(biomeData, biomeName, scene_list, ws, ng, x, y, skipCosmeticScenes = true, gameMode = 'normal') {
	if (!scene_list || scene_list.length === 0) return null;
	const prng = new NollaPrng(0);
	let total_prob = 0;
	for (const scene of scene_list) {
		total_prob += scene.prob;
	}
	let r = prng.ProceduralRandom(ws + ng, x, y) * total_prob;
	for (const scene of scene_list) {
		if (scene.prob <= 0) continue;
		if (r <= scene.prob) {
			if (scene.name === "") return null; // Rolled for no scene
			const pixelSceneKey = getPixelSceneKey(biomeName, scene.name);
			if (!PIXEL_SCENE_DATA[pixelSceneKey]) {
				console.warn(`Pixel scene data not found for key ${pixelSceneKey}. This should not happen because we preload all pixel scene images.`);
				return null;
			}
			const pixelSceneData = PIXEL_SCENE_DATA[pixelSceneKey];
			if (pixelSceneData.isCosmetic && skipCosmeticScenes) {
				// If the scene is purely cosmetic and we're skipping cosmetic scenes, skip it
				return null;
			}
			let outputScene = {
				key: pixelSceneKey,
				name: scene.name, 
				//imgElement: pixelSceneData.imgElement,
				width: pixelSceneData.width,
				height: pixelSceneData.height,
				x: x, 
				y: y, 
				material: null,
				//spawnPoints: pixelSceneData.spawnPoints,
				type: 'pixel_scene'
			};
			// Check all four corners to make sure they are in the same biome
			if (CHECK_PIXEL_SCENE_BIOME) {
				const w = pixelSceneData.width;
				const h = pixelSceneData.height;
				const corners = [
					[x, y],
					[x + w, y],
					[x, y + h],
					[x + w, y + h],
				];
				for (const [cx, cy] of corners) {
					const res = getBiomeAtWorldCoordinates(biomeData, cx, cy, ng > 0, gameMode, true);
					// Reject if the corner's wobbled biome is different (including null)
					if (res.biome !== biomeName) {
						return null;
					}
				}
			}
			// Recolor random materials first so material lookups still work
			let variantKey = '';
			if (scene.color_material) {
				// Sort keys to ensure consistent ordering for caching variants
				const sortedColors = Object.keys(scene.color_material).sort((a, b) => parseInt(a, 16) - parseInt(b, 16));
				for (const color of sortedColors) {
					// Start with the recolored variant
					//let pixelSceneImage = getPixelSceneVariant(pixelSceneKey, variantKey);
					const materials = scene.color_material[color];
					prng.SetRandomSeed(ws + ng, x + 11, y - 21); //?
					let r = prng.ProceduralRandom(ws + ng, x + 11, y - 21); // Note ProceduralRandom returns a value in (0, 1] so this is actually fine
					let mr = Math.ceil(r * materials.length) - 1;
					
					const targetMaterial = materials[mr];
					outputScene.material = targetMaterial;
					let materialColor = MATERIAL_WANG_COLORS[materials[mr]];
					// See if the recolored pixel scene is already cached
					//variantKey += (variantKey !== '' ? '&' : '') + `${color}=${targetMaterial}`;
					// Use material color instead to avoid an extra lookup
					variantKey += (variantKey !== '' ? '&' : '') + `${color}=${materialColor}`;
					/*
					if (!PIXEL_SCENE_DATA[pixelSceneKey].variants[variantKey]) {
						PIXEL_SCENE_DATA[pixelSceneKey].variants[variantKey] = recolorPixelScene(
							pixelSceneImage, 
							parseInt(color, 16), 
							parseInt(materialColor, 16)
						);
						//console.log(`Created variant of pixel scene ${pixelSceneKey} with key ${variantKey}`);
					}
					*/
				}
			}
			// Recolor the pixel scene for the biome if needed
			const finalVariantKey = variantKey + (variantKey !== '' ? '&' : '')
				+ `biome=${biomeName}${underlyingBiomeSuffix(biomeData, pixelSceneData, biomeName, scene.name, x, y, ng, gameMode)}`;
			/*
			if (!PIXEL_SCENE_DATA[pixelSceneKey].variants[finalVariantKey]) {
				PIXEL_SCENE_DATA[pixelSceneKey].variants[finalVariantKey] = recolorPixelSceneForBiome(scene.name, getPixelSceneVariant(pixelSceneKey, variantKey), biomeName);
				//console.log(`Created biome variant of pixel scene ${pixelSceneKey} with key ${finalVariantKey}`);
			}
			*/
			outputScene.variantKey = finalVariantKey;
			//outputScene.imgElement = PIXEL_SCENE_DATA[pixelSceneKey].variants[finalVariantKey];

			//console.log(`Loaded pixel scene ${scene.name} at (${x}, ${y}) in biome ${biomeName}.`);
			return outputScene;
		}
		r -= scene.prob;
	}
	console.log(`Impossible zero probability outcome for pixel scene at (${x}, ${y}), total prob ${total_prob}, r ${r}: ${JSON.stringify(scene_list)}`);
	return null;
}

/** Does this scene contain air pixels / "fill with the biome's material" pixels? */
function classifyPixelSceneColors(data) {
	let hasAir = false;
	let hasBiomeFill = false;
	for (let i = 0; i < data.length; i += 4) {
		const r = data[i], g = data[i + 1], b = data[i + 2];
		if (r === 0 && g === 0 && b === 0x42) hasAir = true;
		else if (r === g && g === b && r > 0) hasBiomeFill = true;
		if (hasAir && hasBiomeFill) break;
	}
	return { hasAir, hasBiomeFill };
}

/**
 * The `@<biome>` suffix a scene's `biome=` variant key carries when its recolor
 * depends on the chunk it landed in, or '' when it does not.
 *
 * The recolor target is the scene's *folder* biome, which for everything under
 * general/ and temple/ is a pseudo-biome shared across the map. Two things it
 * therefore cannot answer: whether the chunk beneath is solid material, which
 * decides if the scene's air may stay transparent; and what color the scene's
 * "fill with the biome's own material" pixels take, since a pseudo-biome has no
 * entry in either color table -- which is what used to paint the orb room floors
 * magenta. Naming the chunk's biome in the variant key answers both, at one
 * cached variant per underlying biome, and only for scenes that contain the
 * class in question.
 */
function underlyingBiomeSuffix(biomeData, sceneData, biomeName, sceneName, x, y, ng, gameMode) {
	// The altars are deliberately never recolored per biome; keep them at one variant.
	if (SCENES_TO_NOT_RECOLOR.includes(sceneName)) return '';
	const needsFillColor = sceneData.hasBiomeFill && TILE_OVERLAY_COLORS[biomeName] === undefined;
	if (!sceneData.hasAir && !needsFillColor) return '';
	const under = getBiomeAtWorldCoordinates(biomeData, x + sceneData.width / 2, y + sceneData.height / 2, ng > 0, gameMode, true)?.biome;
	if (!under || under === biomeName) return '';
	if (needsFillColor) return `@${under}`;
	return terrainFillColorForBiome(under) === undefined ? '' : `@${under}`;
}

/**
 * How a scene stamped in `targetBiome` paints its two biome-dependent color
 * classes: the density ("fill with this biome's own material") class, and air.
 *
 * Shared by the flat recolor and the textured build so the two cannot drift on
 * which biome answers for a pseudo-biome folder, or on when air is opaque.
 */
function sceneBiomePaint(sceneName, targetBiome) {
	// `biome=<folder>@<chunk biome>`: the folder decides the colors, the suffix
	// (underlyingBiomeSuffix) names the biome of the chunk the scene landed in.
	const at = targetBiome.indexOf('@');
	const underlyingBiome = at < 0 ? null : targetBiome.slice(at + 1);
	if (at >= 0) targetBiome = targetBiome.slice(0, at);
	// "the chunk under this scene is solid material", NOT merely "the biome has a
	// fillMaterial": a `sceneOnly` room has one (its scenes' white resolves through
	// it) but its chunk is air, so the scene's air must stay transparent there.
	const fillBiomeUnderScene = (underlyingBiome && terrainFillColorForBiome(underlyingBiome) !== undefined)
		? underlyingBiome : null;

	// A scene's gray/white pixels are the engine's "fill with this biome's own
	// material" class, so in a constant-material biome they must come out as that
	// biome's fill color -- the same one the terrain around them paints. Otherwise
	// they take the hand-authored foreground color, which for these biomes equals
	// the background color and leaves the carved room reading as a flat block.
	// The pseudo-biomes (general/, temple/, spliced/) have no entry in either
	// color table, so their scenes' fill pixels used to come out magenta -- most
	// visibly the orb rooms, whose whole floor is that class. Falling back to the
	// biome under the scene answers it exactly: those pixels are "fill with the
	// chunk's own material", which is what the suffix names.
	const targetColor = sceneMaterialFillColorForBiome(targetBiome)
		?? TILE_OVERLAY_COLORS[targetBiome]
		?? (underlyingBiome ? sceneMaterialFillColorForBiome(underlyingBiome) ?? TILE_OVERLAY_COLORS[underlyingBiome] : undefined)
		?? 0xff00ff;
	let bgColor = BIOME_BACKGROUND_COLORS[targetBiome]
		?? (underlyingBiome ? BIOME_BACKGROUND_COLORS[underlyingBiome] : undefined)
		?? 0x000000;

	// Air over a fill has to punch a visible hole in solid material, so it must
	// not come out the same color as the fill. For friend_1..6 the biome maps
	// give foreground and background the same unauthored pixel, so the "correct"
	// background would erase the room; darken the fill instead, which is roughly
	// what a background reads as next to its own material anyway.
	const fillUnder = terrainFillColorForBiome(fillBiomeUnderScene ?? targetBiome);
	if (fillUnder !== undefined && channelDistance(bgColor, fillUnder) <= AIR_OVER_FILL_TOLERANCE) {
		bgColor = ((Math.round(((fillUnder >> 16) & 0xFF) * AIR_OVER_FILL_DARKEN) << 16)
			| (Math.round(((fillUnder >> 8) & 0xFF) * AIR_OVER_FILL_DARKEN) << 8)
			| Math.round((fillUnder & 0xFF) * AIR_OVER_FILL_DARKEN));
	}

	// Transparent air is only right when nothing is painted underneath: it lets
	// whatever is already on the canvas show through, which for a wang biome is
	// the layer's own terrain. In a constant-material fill biome the whole chunk
	// is solid, so transparent air would leave the carved room filled in and
	// invisible -- the scene has to punch the hole itself, in the color the
	// background layer would have shown. Hiisi base is the hand-found instance of
	// the same rule.
	//
	// Both tests ask "does this chunk actually emit a fill layer", so a
	// `sceneOnly` room falls through to the transparent branch: its chunk is air,
	// and the scene's air must read as the cave background the game shows there,
	// not as an opaque plug.
	//
	// The textured build does not need any of this -- it erases the terrain under
	// its air with a real mask pass -- so it only honors the authored exceptions.
	const opaqueOverFill = targetBiome === "snowcastle" || !!fillBiomeUnderScene
		|| terrainFillColorForBiome(targetBiome) !== undefined;
	const authoredAirAlpha = PIXEL_SCENE_AIR_TRANSPARENCY_EXCEPTIONS[sceneName] ?? 0x00;

	return {
		targetBiome, underlyingBiome, targetColor, bgColor,
		airAlpha: opaqueOverFill ? 0xff : authoredAirAlpha,
		texturedAirAlpha: authoredAirAlpha,
	};
}

export function recolorPixelSceneForBiome(sceneName, sourceData, targetBiome) {
	//const recolorMaterials = document.getElementById('recolor-materials').checked;
	const recolorMaterials = appSettings.recolorMaterials;

	const outData = new Uint8Array(sourceData.length);
	outData.set(sourceData);

	// Some scene name exceptions because this just isn't working
	const paint = sceneBiomePaint(sceneName, targetBiome);
	const targetColor = paint.targetColor;
	const bgColor = paint.bgColor;
	const airAlpha = paint.airAlpha;
	let targetR = (targetColor >> 16) & 0xFF;
	let targetG = (targetColor >> 8) & 0xFF;
	let targetB = targetColor & 0xFF;
	let bgColorR = (bgColor >> 16) & 0xFF;
	let bgColorG = (bgColor >> 8) & 0xFF;
	let bgColorB = bgColor & 0xFF;
	/*
	const biomeMapWidth = getWorldSize(app.ngPlusCount > 0);
	if (targetR === 255 && targetG === 0 && targetB === 255) {
		// As a fallback, use the color of the biome map?
		// TODO: Currently using app references here when I probably shouldn't
		// Using center of the pixel scene, but it shouldn't really matter
		const chunkX = (Math.floor((biomeMapWidth * 256 + x + width/2) / 512) % getWorldSize(app.ngPlusCount > 0) + getWorldSize(app.ngPlusCount > 0)) % getWorldSize(app.ngPlusCount > 0);
		let chunkY = Math.floor((14*512 + y + height/2) / 512);
		if (chunkY < 0) chunkY = 0;
		if (chunkY > 47) chunkY = 47;
		const bgColorIdx = (chunkY * biomeMapWidth + chunkX)*3;
		const bgColor = (app.recolorOffscreenBuffer[bgColorIdx] << 16) | (app.recolorOffscreenBuffer[bgColorIdx + 1] << 8) | app.recolorOffscreenBuffer[bgColorIdx + 2];
		if (y > 22000) {
			console.log(bgColor, BIOME_BACKGROUND_COLORS["the_end"] & 0xffffff)
		}
		// TODO: Some attempt to make the background color not exactly the same as the terrain color... Need to just get a better background and foreground.
		targetR = Math.floor(app.recolorOffscreenBuffer[bgColorIdx] * 0.75);
		targetG = Math.floor(app.recolorOffscreenBuffer[bgColorIdx + 1] * 0.75);
		targetB = Math.floor(app.recolorOffscreenBuffer[bgColorIdx + 2] * 0.75);
		bgColorR = 0;
		bgColorG = 0;
		bgColorB = 0;
	}
	*/

	for (let i = 0; i < outData.length; i += 4) {
		const r = outData[i];
		const g = outData[i + 1];
		const b = outData[i + 2];

		// Handle Grays (Material Recolor)
		if (r === g && g === b && r > 0) {
			outData[i] = targetR;
			outData[i + 1] = targetG;
			outData[i + 2] = targetB;
			//outData[i + 3] = targetA;
		} 
		// Replace Air with Background
		else if (r === 0x00 && g === 0x00 && b === 0x42) {
			outData[i] = bgColorR;
			outData[i + 1] = bgColorG;
			outData[i + 2] = bgColorB;
			outData[i + 3] = airAlpha;
		}
		// Recolor Wang Colors
		else if (recolorMaterials && (r > 0 || g > 0 || b > 0)) {
			const rgb = (r << 16) | (g << 8) | b;
			const matColor = MATERIAL_COLOR_CONVERSION[rgb];
			if (matColor) {
				outData[i] = (matColor >> 16) & 0xFF;
				outData[i + 1] = (matColor >> 8) & 0xFF;
				outData[i + 2] = matColor & 0xFF;
			}
		}
	}

	return outData;
}

// Width and height are not actually needed here
export function recolorPixelScene(sourceData, sourceColor, targetColor) {
    const outData = new Uint8Array(sourceData.length);
	outData.set(sourceData);

	const sourceR = (sourceColor >> 16) & 0xFF;
	const sourceG = (sourceColor >> 8) & 0xFF;
	const sourceB = sourceColor & 0xFF;

	const targetR = (targetColor >> 16) & 0xFF;
	const targetG = (targetColor >> 8) & 0xFF;
	const targetB = targetColor & 0xFF;

    for (let i = 0; i < outData.length; i += 4) {
        const r = outData[i];
		const g = outData[i + 1];
		const b = outData[i + 2];
		if (r === sourceR && g === sourceG && b === sourceB) {
			outData[i] = targetR;
			outData[i + 1] = targetG;
			outData[i + 2] = targetB;
		}
    }

    return outData;
}
// ---------------------------------------------------------------------------
// Engine-faithful pixel scene texturing
//
// The game does not paint a stamped scene in flat material colors. Every cell it
// places gets its color from the material's materials_gfx texture, sampled at the
// cell's ABSOLUTE world coordinates with a negative-safe modulo
// (CellFactory_GetCellColor @0x007044a0) -- exactly the rule the GL terrain
// shader already reproduces for terrain. Two consequences for this module:
//
//  * the answer depends on where the scene landed, so a recolored variant can no
//    longer be shared by every instance of the same scene. The variant cache below
//    keeps doing what it is good at (material SUBSTITUTION, which is
//    position-independent), and the texturing happens per instance when its
//    bitmap is built.
//  * a scene's white/gray pixels are density 1.0 fed to the biome's
//    <MaterialComponent> bands, not a single flat color -- and the rare gates in
//    those bands are position-dependent too. band_select.js runs the engine's own
//    chooser for them.
//
// Both modules are pulled in dynamically so the overlay/search workers, which
// import this file for the flat recolor and the material lookups, never load the
// 270 KB engine tables or the material atlas.
// ---------------------------------------------------------------------------

let sceneTextureModules = null;   // { atlas: <material_atlas.js>, bands: <band_select.js> }
let sceneTextureLoading = null;

/** Starts (or joins) the one-time load of the atlas + band tables. Main thread. */
export function initPixelSceneTextures() {
	return sceneTextureLoading ??= (async () => {
		const [atlas, bands] = await Promise.all([
			import('./gl/material_atlas.js'),
			import('./engine_resolve/band_select.js'),
		]);
		await atlas.initMaterialAtlas();
		sceneTextureModules = { atlas, bands };
		return sceneTextureModules;
	})().catch((err) => {
		console.warn('[pixel scenes] material textures unavailable, staying on flat colors:', err);
		return null;
	});
}

/**
 * The loaded atlas when scene texturing is both enabled and ready, else null.
 *
 * Gated exactly as the GL terrain's own material textures are (app.js passes
 * `materialTextures && recolorMaterials` to the renderer), so the one toggle
 * moves scenes and terrain together and "material colors off" still means flat.
 */
function sceneTextureAtlas() {
	if (!appSettings.materialTextures || !appSettings.recolorMaterials || !sceneTextureModules) return null;
	return sceneTextureModules.atlas.getMaterialAtlas();
}

// 0xRRGGBB wang color -> material name, from MATERIAL_COLOR_LOOKUP's hex keys.
let wangColorToMaterial = null;
function materialForWangColor(rgb) {
	if (!wangColorToMaterial) {
		wangColorToMaterial = new Map();
		for (const [hex, name] of Object.entries(MATERIAL_COLOR_LOOKUP)) {
			wangColorToMaterial.set(parseInt(hex, 16) & 0xffffff, name);
		}
	}
	return wangColorToMaterial.get(rgb);
}

/**
 * The BIOME_ENGINE entry whose <MaterialComponent> bands answer this scene's
 * density class, preferring the scene's own folder biome and falling back to the
 * biome of the chunk it landed in (which is what a pseudo-biome folder means).
 * Only an entry that actually carries bands counts: the constant-material rooms
 * (temple_altar and friends) have an empty table and are answered by their
 * fillMaterial instead.
 *
 * Deliberately NOT gated on `biome.supported`. That flag is about the TOPOLOGY
 * resolve -- whether the carve branch, the inside-noise variant and the density
 * modifier of this biome are ported -- and a scene's density class runs none of
 * it: the coverage is a literal 1.0 that the caller feeds straight into
 * ComputeMaterialNoiseDensity. The band list is the only thing that has to be
 * complete, and it is: of the 174 biomes in the table exactly one (lava_90percent
 * #ffa717) loses a band to `unsupportedBand`, and it loses its only one, so the
 * `bands.length` test below already excludes it.
 *
 * Requiring `supported` cost the 41 biomes that carry bands but fail the topology
 * checks -- every orb room, every essence room, the gun/null/rock/song/moon rooms,
 * secret_lab, the pyramid interiors -- which are exactly the rooms whose entire
 * content is a stamped scene. They all fell back to a single flat fillMaterial.
 * Measured against the game on the orb room (groundtruth/batch3/orbroom, seed
 * 786433191): the flat fill matched 52.3% of the scene's 48,936 white pixels,
 * the band chooser matches 99.4% -- including the 17.9% that are AIR, which is
 * the orb room's background art showing through its floor.
 */
function densityBiomeFor(bands, targetBiome, underlyingBiome) {
	for (const name of [targetBiome, underlyingBiome]) {
		if (!name) continue;
		const conf = GENERATOR_CONFIG[name];
		if (!conf) continue;
		const biome = bands.engineBiomeForColor(conf.color & 0xffffff);
		// The NAME rides along so the hover readout can say which biome's bands
		// answered, which is the whole point of the pseudo-biome fallback.
		if (biome && biome.bands.length) return { entry: biome, biomeName: name };
	}
	return null;
}

/** The fillMaterial that answers a scene's density class where no band table does. */
function densityFillMaterialFor(targetBiome, underlyingBiome) {
	for (const name of [targetBiome, underlyingBiome]) {
		const conf = name ? GENERATOR_CONFIG[name] : null;
		const material = conf ? FILL_BIOME_MATERIALS[conf.color & 0xffffff] : undefined;
		if (material !== undefined) return { material, biomeName: name };
	}
	return null;
}

/**
 * The two biome names a variant key's `biome=` part carries: the scene's folder
 * biome and, after `@`, the biome of the chunk it landed in.
 */
function variantBiomes(variantKey) {
	let biome = 'general';
	for (const part of (variantKey || '').split('&')) {
		const eq = part.indexOf('=');
		if (eq >= 0 && part.slice(0, eq) === 'biome') biome = part.slice(eq + 1);
	}
	const at = biome.indexOf('@');
	return {
		targetBiome: at < 0 ? biome : biome.slice(0, at),
		underlyingBiome: at < 0 ? null : biome.slice(at + 1),
	};
}

/**
 * What a stamped scene's DENSITY CLASS -- its white/gray pixels, the engine's
 * "fill with this biome's own material" -- resolves to at one world pixel.
 *
 * The same lookup texturePixelSceneForBiome() runs per pixel while it builds an
 * instance, pulled out so the hover readout can answer for those pixels too
 * (js/utils.js getMaterialProvenanceAtWorldCoordinates). Without it the readout
 * walked the scene PNG, found a colour no material table knows, and reported
 * `Origin: air` over solid rock -- the blind spot that made the orb rooms look
 * empty while the renderer was painting them correctly.
 *
 * Returns null when nothing can answer (no bands loaded and no fill material).
 * `{ material: null, via: 'bands' }` is NOT that case: it means the band table
 * accepted nothing at density 1.0, which is a real AIR answer.
 *
 * @param {string} variantKey  the instance's variant key (only `biome=` is read)
 * @param {number} worldX      absolute world coordinates of the pixel
 * @param {number} worldY
 * @returns {{material: string|null, biomeName: string, via: 'bands'|'fill'}|null}
 */
export function sceneDensityClassAt(variantKey, worldX, worldY) {
	const { targetBiome, underlyingBiome } = variantBiomes(variantKey);
	// Gated exactly as the build is: with material textures off the scene paints
	// the flat fill colour, so claiming a band's answer would name a material the
	// picture on screen does not show.
	const bands = sceneTextureAtlas() ? sceneTextureModules.bands : null;
	const densityBiome = bands ? densityBiomeFor(bands, targetBiome, underlyingBiome) : null;
	if (densityBiome) {
		const id = bands.selectComponentForCell(densityBiome.entry, worldX, worldY,
			bands.computeMaterialNoiseDensity(worldX, worldY, 1.0));
		return { material: id < 0 ? null : bands.materialNameForId(id), biomeName: densityBiome.biomeName, via: 'bands' };
	}
	const fill = densityFillMaterialFor(targetBiome, underlyingBiome);
	return fill ? { material: fill.material, biomeName: fill.biomeName, via: 'fill' } : null;
}

/**
 * Per-instance engine-faithful build of one stamped pixel scene.
 *
 * `sourceData` is the scene PNG after its material substitutions (so its pixels
 * are still wang colors); (worldX, worldY) is where its top-left corner lands in
 * generation world space. Returns { pixels, airMask }: the RGBA image to draw,
 * and an RGBA mask that is opaque exactly on the scene's FORCE AIR pixels, or
 * null when it has none.
 *
 * Air (#000042) erases the world instead of painting it, so the caller draws the
 * mask with `destination-out` before the image. That is what makes air correct
 * over the engine-resolved GL terrain, which paints every chunk -- the old
 * "opaque background color over a fill biome" trick only covered the chunks
 * telescope itself filled.
 */
export function texturePixelSceneForBiome(sceneName, sourceData, width, height, targetBiome, worldX, worldY) {
	const { atlas: atlasMod, bands } = sceneTextureModules;
	const atlas = atlasMod.getMaterialAtlas();
	const recolorMaterials = appSettings.recolorMaterials;
	const paint = sceneBiomePaint(sceneName, targetBiome);
	const airAlpha = paint.texturedAirAlpha;
	const bgColorR = (paint.bgColor >> 16) & 0xFF;
	const bgColorG = (paint.bgColor >> 8) & 0xFF;
	const bgColorB = paint.bgColor & 0xFF;

	// The density class, resolved per pixel. A scene's gray pixels are fully solid
	// coverage, but the engine never hands raw coverage to the band chooser: it
	// runs it through ComputeMaterialNoiseDensity first, which warps the position
	// by a value-noise field and adds a simplex term. That is why a uniformly
	// white region comes out of the game as veins of several materials rather than
	// one flat answer, and it is the same call the GL terrain under the scene makes.
	const densityBiome = densityBiomeFor(bands, paint.targetBiome, paint.underlyingBiome);

	// How one material paints: its atlas rect when it has a texture, else its flat
	// display color (which is what the engine falls back to as well), composited
	// with the material's XML alpha (water 0xA0) exactly as the engine's cell
	// grid blends liquids/gasses over the background layer. Memoized -- a scene
	// uses a handful of materials across hundreds of thousands of pixels.
	const recipeByName = new Map();
	const recipeForMaterial = (name, fallbackFlat) => {
		let recipe = recipeByName.get(name);
		if (recipe === undefined) {
			const wang = MATERIAL_WANG_COLORS[name];
			recipe = {
				entry: atlasMod.materialAtlasEntry(atlas, name),
				flat: wang === undefined ? fallbackFlat : materialDisplayColor(name),
				alpha: wang === undefined ? 255 : atlasMod.materialAlpha(name),
			};
			recipeByName.set(name, recipe);
		}
		return recipe;
	};
	// The density class' answer where no band table covers it: the biome's own
	// fillMaterial, textured like any other material rather than flattened.
	const fillMaterial = densityFillMaterialFor(paint.targetBiome, paint.underlyingBiome);
	const fillRecipe = fillMaterial
		? recipeForMaterial(fillMaterial.material, paint.targetColor)
		: { entry: 0, flat: paint.targetColor, alpha: 255 };

	const densityRecipes = new Map();
	const densityRecipeFor = (id) => {
		let recipe = densityRecipes.get(id);
		if (recipe === undefined) {
			const name = id < 0 ? null : bands.materialNameForId(id);
			recipe = name ? recipeForMaterial(name, paint.targetColor) : fillRecipe;
			densityRecipes.set(id, recipe);
		}
		return recipe;
	};
	// Wang color -> the same recipe, via the material that owns the color.
	const wangRecipes = new Map();
	const wangRecipeFor = (rgb) => {
		let recipe = wangRecipes.get(rgb);
		if (recipe === undefined) {
			const name = materialForWangColor(rgb);
			recipe = name
				? recipeForMaterial(name, (recolorMaterials ? MATERIAL_COLOR_CONVERSION[rgb] : undefined) ?? rgb)
				: { entry: 0, flat: (recolorMaterials ? MATERIAL_COLOR_CONVERSION[rgb] : undefined) ?? rgb, alpha: 255 };
			wangRecipes.set(rgb, recipe);
		}
		return recipe;
	};

	const outData = new Uint8Array(sourceData.length);
	outData.set(sourceData);
	let airMask = null;

	for (let i = 0, p = 0; i < outData.length; i += 4, p++) {
		if (outData[i + 3] === 0) continue;   // untouched: alpha 0 / #000000
		const r = outData[i], g = outData[i + 1], b = outData[i + 2];

		// FORCE AIR: erases the world rather than painting it, so it goes in the
		// mask -- unless this scene is one of the few whose art wants its air
		// painted solid, in which case the image covers the same pixel and the mask
		// must leave it alone (that keeps the two passes disjoint, so the draw site
		// can run them in either order).
		if (r === 0x00 && g === 0x00 && b === 0x42) {
			if (airAlpha === 0x00) {
				if (!airMask) airMask = new Uint8Array(sourceData.length);
				airMask[i + 3] = 0xff;
			}
			outData[i] = bgColorR;
			outData[i + 1] = bgColorG;
			outData[i + 2] = bgColorB;
			outData[i + 3] = airAlpha;
			continue;
		}

		const wx = worldX + (p % width);
		const wy = worldY + ((p / width) | 0);

		// Full coverage through the biome's <MaterialComponent> bands for the gray
		// class; the wang color's own material for everything else.
		//
		// A band table that accepts nothing at density 1.0 answers AIR, and that is
		// a real answer rather than a gap: the orb room's floor is 17.9% air in the
		// game's own dump and the chooser predicts it (see densityBiomeFor). So a
		// -1 from a table we have goes into the erase mask exactly like FORCE AIR,
		// which is what lets a room's background art show through its own floor.
		// Only a biome with NO band table falls back to the flat fillMaterial.
		let recipe;
		if (r === g && g === b && r > 0) {
			if (densityBiome) {
				const id = bands.selectComponentForCell(densityBiome.entry, wx, wy,
					bands.computeMaterialNoiseDensity(wx, wy, 1.0));
				if (id < 0) {
					if (!airMask) airMask = new Uint8Array(sourceData.length);
					airMask[i + 3] = 0xff;
					outData[i + 3] = 0x00;
					continue;
				}
				recipe = densityRecipeFor(id);
			}
			else recipe = fillRecipe;
		}
		else recipe = wangRecipeFor((r << 16) | (g << 8) | b);
		const { entry, flat, alpha } = recipe;

		let a = alpha;
		if (entry > 0) {
			// Textured materials take the texel's own alpha (same rule as the GL
			// terrain shader); a fully transparent texel places no cell at all.
			const texel = atlasMod.materialTexelRGBA(atlas, entry, wx, wy);
			if (texel < 0) { outData[i + 3] = 0x00; continue; }
			a = (texel >>> 24) & 0xFF;
			outData[i] = (texel >> 16) & 0xFF;
			outData[i + 1] = (texel >> 8) & 0xFF;
			outData[i + 2] = texel & 0xFF;
		} else {
			outData[i] = (flat >> 16) & 0xFF;
			outData[i + 1] = (flat >> 8) & 0xFF;
			outData[i + 2] = flat & 0xFF;
		}
		if (a < 255) {
			// A translucent cell (liquid, gas) replaces the world cell under it
			// and blends over the BACKGROUND, so it must also erase the terrain:
			// mask first, translucent pixel second, background refilled behind by
			// the draw site's destination-over pass.
			outData[i + 3] = a;
			if (!airMask) airMask = new Uint8Array(sourceData.length);
			airMask[i + 3] = 0xff;
		}
	}

	return { pixels: outData, airMask };
}

// ---------------------------------------------------------------------------
// Scene material identity, for the edge-decal pass
//
// PixelScene_TryPaintEntry @0x00880fb0 runs its OWN EdgeGraphics pass after
// writing a scene's cells (BiomeMaterials_PaintEdgeMaterial @0x00721da0), so
// scene-painted materials get dressed exactly like generated terrain. That pass
// needs the material IDENTITY of every scene pixel, which is the same
// classification texturePixelSceneForBiome() runs for colors:
//   alpha 0 / #000000  -> untouched, the world cell under it stays
//   #000042            -> FORCE AIR, the world cell is removed
//   gray/white         -> density 1.0 through the biome's band chooser
//   anything else      -> the wang color's own material
//
// The gates are on material IDENTITY alone. A scene's _visual.png art overrides
// only the cell COLOR, never its material, so art cells participate in the edge
// decisions exactly like the material under them -- and the engine happily
// stamps over art at a real material border. The one thing that stops a scene's
// pass is `skip_edge_textures` (js/pixel_scene_edge_flags.js), which suppresses
// the restamp entirely while the scene's cells still erase the terrain pass.
// ---------------------------------------------------------------------------

/** The scene leaves this pixel alone; whatever cell the world has stays. */
export const SCENE_MAT_UNTOUCHED = -2;
/** A painted cell whose material the engine tables don't carry (prop art,
 *  unmapped wang colors). It blocks edges like any solid cell but can never
 *  stamp decals of its own. Large so it can live in an Int16Array beside
 *  real ids without colliding with them. */
export const SCENE_MAT_UNKNOWN = 0x7ffe;

/**
 * The per-pixel material ids one stamped scene instance paints, in the engine's
 * classification above. `bands` is the engine_resolve/band_select module (passed
 * in so this file keeps not importing the engine tables statically).
 *
 * Returns { grid: Int16Array, width, height, x, y, skipEdges } or null when the
 * scene's pixels aren't loaded. `skipEdges` is the game's `skip_edge_textures`:
 * the cells still erase the terrain stamps under them, but no restamp runs.
 */
export function pixelSceneMaterialGrid(scene, bands) {
	const data = PIXEL_SCENE_DATA[scene.key];
	if (!data || !ArrayBuffer.isView(data.imgElement)) return null;
	// Material substitutions first, in wang color space, exactly as the bitmap
	// build runs them; the biome part names the band table for the gray class.
	let pixels = data.imgElement;
	let biome = 'general';
	for (const part of (scene.variantKey || '').split('&')) {
		const eq = part.indexOf('=');
		if (eq < 0) continue;
		if (part.slice(0, eq) === 'biome') biome = part.slice(eq + 1);
		else pixels = recolorPixelScene(pixels, parseInt(part.slice(0, eq), 16), parseInt(part.slice(eq + 1), 16));
	}
	const at = biome.indexOf('@');
	const underlyingBiome = at < 0 ? null : biome.slice(at + 1);
	const targetBiome = at < 0 ? biome : biome.slice(0, at);
	const densityBiome = densityBiomeFor(bands, targetBiome, underlyingBiome);
	const fillMaterial = densityFillMaterialFor(targetBiome, underlyingBiome);
	const fillId = fillMaterial ? bands.materialIdForName(fillMaterial.material) : -1;

	const w = data.width, h = data.height;
	const grid = new Int16Array(w * h).fill(SCENE_MAT_UNTOUCHED);
	const wangIds = new Map();
	for (let p = 0, i = 0; p < w * h; p++, i += 4) {
		if (pixels[i + 3] === 0) continue;
		const r = pixels[i], g = pixels[i + 1], b = pixels[i + 2];
		if (r === 0x00 && g === 0x00 && b === 0x42) { grid[p] = 0; continue; }
		if (r === g && g === b && r > 0) {
			const wx = scene.x + (p % w), wy = scene.y + ((p / w) | 0);
			const id = densityBiome
				? bands.selectComponentForCell(densityBiome.entry, wx, wy,
					bands.computeMaterialNoiseDensity(wx, wy, 1.0))
				: -1;
			// Same rule the bitmap build paints: a table we have answering -1
			// is AIR (id 0), and only a biome with no table at all falls back
			// to its flat fill material.
			grid[p] = id >= 0 ? id
				: densityBiome ? 0
					: (fillId >= 0 ? fillId : SCENE_MAT_UNKNOWN);
			continue;
		}
		const rgb = (r << 16) | (g << 8) | b;
		let id = wangIds.get(rgb);
		if (id === undefined) {
			const name = materialForWangColor(rgb);
			id = name ? bands.materialIdForName(name) : -1;
			wangIds.set(rgb, id);
		}
		grid[p] = id >= 0 ? id : SCENE_MAT_UNKNOWN;
	}
	return {
		grid, width: w, height: h, x: scene.x, y: scene.y,
		skipEdges: !!data.skipEdgeTextures,
		// The colors-file coverage mask. The scene's edge pass is gated on it as
		// a whole (js/edge_decals.js sceneStampsAnyEdge), so the decal pass needs
		// it alongside the materials.
		artMask: data.artMask || null,
	};
}
