// GENERATED by tools/gen_scene_backgrounds.mjs -- do not edit.
// Scene key (`${getBiomeAlias(biome)}/${sceneName}`, the data/pixel_scenes
// path) -> the repo-relative background image the engine draws behind that
// scene (LoadPixelScene's background_filename, z = 50). The image is blitted
// 1:1 at the scene's top-left, so a background larger or smaller than the scene
// hangs off / falls short exactly as it does in game.
export const SCENE_BACKGROUNDS = {
	"coalmine/oiltank_puzzle": "data/backgrounds/biome_impl/coalmine/oiltank_puzzle_background.png",
	"coalmine/receptacle_oil": "data/backgrounds/biome_impl/coalmine/receptacle_oil_background.png",
	"excavationsite/cube_chamber": "data/backgrounds/biome_impl/excavationsite/cube_chamber_background.png",
	"excavationsite/machine_1": "data/backgrounds/biome_impl/excavationsite/machine_1_background.png",
	"excavationsite/machine_1_alt": "data/backgrounds/biome_impl/excavationsite/machine_1_background.png",
	"excavationsite/machine_2": "data/backgrounds/biome_impl/excavationsite/machine_2_background.png",
	"excavationsite/machine_2_alt": "data/backgrounds/biome_impl/excavationsite/machine_2_background.png",
	"excavationsite/machine_3b": "data/backgrounds/biome_impl/excavationsite/machine_3b_background.png",
	"excavationsite/machine_3b_alt": "data/backgrounds/biome_impl/excavationsite/machine_3b_background.png",
	"excavationsite/machine_4": "data/backgrounds/biome_impl/excavationsite/machine_4_background.png",
	"excavationsite/machine_4_alt": "data/backgrounds/biome_impl/excavationsite/machine_4_background.png",
	"excavationsite/machine_5": "data/backgrounds/biome_impl/excavationsite/machine_5_background.png",
	"excavationsite/machine_5_alt": "data/backgrounds/biome_impl/excavationsite/machine_5_background.png",
	"excavationsite/machine_7": "data/backgrounds/biome_impl/excavationsite/machine_5_background.png",
	"excavationsite/machine_7_alt": "data/backgrounds/biome_impl/excavationsite/machine_5_background.png",
	"excavationsite/receptacle_steam": "data/backgrounds/biome_impl/excavationsite/receptacle_steam_background.png",
	"general/acidtank": "data/backgrounds/biome_impl/acidtank_background.png",
	"general/acidtank_2": "data/backgrounds/biome_impl/acidtank_2_background.png",
	"general/boss_victoryroom": "data/backgrounds/biome_impl/boss_victoryroom_background.png",
	"general/bunker": "data/backgrounds/biome_impl/bunker_background.png",
	"general/bunker2": "data/backgrounds/biome_impl/bunker_background.png",
	"general/cavern": "data/backgrounds/biome_impl/cavern_background.png",
	"general/dragoncave": "data/backgrounds/biome_impl/dragoncave_background.png",
	"general/essenceroom": "data/backgrounds/biome_impl/essenceroom_background_with_diamond.png",
	"general/essenceroom_submerged": "data/backgrounds/biome_impl/essenceroom_background_with_diamond.png",
	"general/fishing_hut": "data/backgrounds/biome_impl/fishing_hut_background.png",
	"general/greed_treasure": "data/backgrounds/biome_impl/greed_treasure_background.png",
	"general/lavalake_racing": "data/backgrounds/biome_impl/lavalake_racing_background.png",
	"general/mystery_teleport": "data/backgrounds/biome_impl/essenceroom_background.png",
	"general/orbroom": "data/backgrounds/biome_impl/orbroom_background.png",
	"general/robot_egg": "data/backgrounds/biome_impl/robot_egg_background.png",
	"general/secret_lab": "data/backgrounds/biome_impl/secret_lab_background.png",
	"general/wizardcave_entrance": "data/backgrounds/biome_impl/wizardcave_entrance_background.png",
	"mountain/hall": "data/backgrounds/biome_impl/mountain/hall_background.png",
	"mountain/left": "data/backgrounds/biome_impl/mountain/left_background.png",
	"mountain/left_entrance": "data/backgrounds/biome_impl/mountain/left_entrance_background.png",
	"mountain/left_entrance_below": "data/backgrounds/biome_impl/mountain/left_entrance_below_background.png",
	"mountain/left_stub": "data/backgrounds/biome_impl/mountain/left_stub_background.png",
	"mountain/right": "data/backgrounds/biome_impl/mountain/right_background.png",
	"mountain/right_2": "data/backgrounds/biome_impl/mountain/right_background.png",
	"mountain/right_entrance": "data/backgrounds/biome_impl/mountain/right_entrance_background.png",
	"mountain/right_stub": "data/backgrounds/biome_impl/mountain/right_stub_background.png",
	"pyramid/entrance": "data/backgrounds/biome_impl/pyramid/entrance_background.png",
	"pyramid/top": "data/backgrounds/biome_impl/pyramid/top_background.png",
	"rainforest/hut01": "data/backgrounds/biome_impl/rainforest/hut01_background.png",
	"rainforest/plantlife": "data/backgrounds/biome_impl/rainforest/plantlife_background.png",
	"rainforest_dark/hut01": "data/backgrounds/biome_impl/rainforest/hut01_background.png",
	"rainforest_dark/plantlife": "data/backgrounds/biome_impl/rainforest/plantlife_background.png",
	"rainforest_open/hut01": "data/backgrounds/biome_impl/rainforest/hut01_background.png",
	"rainforest_open/plantlife": "data/backgrounds/biome_impl/rainforest/plantlife_background.png",
	"snowcastle/bar": "data/backgrounds/biome_impl/snowcastle/bar_background.png",
	"snowcastle/bedroom": "data/backgrounds/biome_impl/snowcastle/bedroom_background.png",
	"snowcastle/drill": "data/backgrounds/biome_impl/snowcastle/drill_background.png",
	"snowcastle/forge": "data/backgrounds/biome_impl/snowcastle/forge_background.png",
	"snowcastle/greenhouse": "data/backgrounds/biome_impl/snowcastle/greenhouse_background.png",
	"snowcastle/hourglass_chamber": "data/backgrounds/biome_impl/snowcastle/hourglass_chamber_background.png",
	"snowcastle/pod_large_01": "data/backgrounds/biome_impl/snowcastle/pod_large_01_background.png",
	"snowcastle/pod_small_l_01": "data/backgrounds/biome_impl/snowcastle/pod_small_l_01_background.png",
	"snowcastle/pod_small_r_01": "data/backgrounds/biome_impl/snowcastle/pod_small_r_01_background.png",
	"snowcastle/sauna": "data/backgrounds/biome_impl/snowcastle/sauna_background.png",
	"snowcastle/side_cavern_left": "data/backgrounds/biome_impl/snowcastle/side_cavern_left_background.png",
	"snowcastle/side_cavern_right": "data/backgrounds/biome_impl/snowcastle/side_cavern_right_background.png",
	"snowcave/acidtank": "data/backgrounds/biome_impl/acidtank_background.png",
	"snowcave/acidtank_2": "data/backgrounds/biome_impl/acidtank_2_background.png",
	"snowcave/horizontalobservatory": "data/backgrounds/biome_impl/snowcave/horizontalobservatory_background.png",
	"snowcave/horizontalobservatory2": "data/backgrounds/biome_impl/snowcave/horizontalobservatory2_background.png",
	"snowcave/horizontalobservatory3": "data/backgrounds/biome_impl/snowcave/horizontalobservatory3_background.png",
	"snowcave/puzzle_capsule": "data/backgrounds/biome_impl/snowcave/puzzle_capsule_background.png",
	"snowcave/puzzle_capsule_b": "data/backgrounds/biome_impl/snowcave/puzzle_capsule_b_background.png",
	"snowcave/receptacle_water": "data/backgrounds/biome_impl/snowcave/receptacle_water_background.png",
	"snowcave/snowcastle": "data/backgrounds/biome_impl/snowcave/snowcastle_background.png",
	"snowcave/tinyobservatory": "data/backgrounds/biome_impl/snowcave/tinyobservatory_background.png",
	"snowcave/tinyobservatory2": "data/backgrounds/biome_impl/snowcave/tinyobservatory2_background.png",
	"snowcave/verticalobservatory": "data/backgrounds/biome_impl/snowcave/verticalobservatory_background.png",
	"snowcave/verticalobservatory2": "data/backgrounds/biome_impl/snowcave/verticalobservatory2_background.png",
	"snowcave/verticalobservatory2_alt": "data/backgrounds/biome_impl/snowcave/verticalobservatory2_background.png",
	"snowcave/verticalobservatory_alt": "data/backgrounds/biome_impl/snowcave/verticalobservatory_background.png",
	"temple/altar": "data/backgrounds/biome_impl/temple/altar_background.png",
	"temple/altar_empty": "data/backgrounds/biome_impl/temple/altar_background.png",
	"temple/altar_left": "data/backgrounds/biome_impl/temple/altar_left_background.png",
	"temple/altar_right": "data/backgrounds/biome_impl/temple/altar_right_background.png",
	"temple/altar_right_snowcastle": "data/backgrounds/biome_impl/temple/altar_right_background.png",
	"vault/acidtank": "data/backgrounds/biome_impl/vault/acidtank_background.png",
	"vault/brain_room": "data/backgrounds/biome_impl/vault/brain_room_background.png",
	"vault/catwalk_01": "data/backgrounds/biome_impl/vault/catwalk_01_background.png",
	"vault/catwalk_02": "data/backgrounds/biome_impl/vault/catwalk_02_background.png",
	"vault/catwalk_02b": "data/backgrounds/biome_impl/vault/catwalk_02b_background.png",
	"vault/catwalk_03": "data/backgrounds/biome_impl/vault/catwalk_03_background.png",
	"vault/catwalk_04": "data/backgrounds/biome_impl/vault/catwalk_04_background.png",
	"vault/electric_tunnel_room": "data/backgrounds/biome_impl/vault/electric_tunnel_room_background.png",
	"vault/lab": "data/backgrounds/biome_impl/vault/lab_background.png",
	"vault/lab2": "data/backgrounds/biome_impl/vault/lab2_background.png",
	"vault/lab3": "data/backgrounds/biome_impl/vault/lab3_background.png",
	"vault/lab_puzzle": "data/backgrounds/biome_impl/vault/lab_puzzle_background.png"
};

// biome -> scene name -> background, for the (biome, scene) pairs where the
// biome's OWN lua passes different art than the map above. One scene PNG can be
// stamped by many biomes with different backgrounds: essenceroom.png is loaded
// by nine biome scripts, three of which (rock_room, moon_room, essenceroom_air)
// pass the 88%-transparent essenceroom_background_diamond.png instead of the
// opaque essenceroom_background_with_diamond.png, so in those three the biome
// backdrop shows through the room. A placement carries the biome it spawned for,
// so the scene loader checks here first (js/pixel_scene_generation.js).
export const SCENE_BACKGROUNDS_BY_BIOME = {
	"essenceroom_air": {
		"essenceroom": "data/backgrounds/biome_impl/essenceroom_background_diamond.png"
	},
	"moon_room": {
		"essenceroom": "data/backgrounds/biome_impl/essenceroom_background_diamond.png"
	},
	"rock_room": {
		"essenceroom": "data/backgrounds/biome_impl/essenceroom_background_diamond.png"
	}
};
