// Exports the game's pixel-scene "visual" (cell-color override) PNGs into
// data/pixel_scenes/ and generates js/pixel_scene_visuals.js, the manifest the
// scene loader uses to know which scenes have one.
//
// The engine's LoadPixelScene(materials, colors, x, y, background) paints each
// cell's color from the colors image where it has alpha, overriding the
// material's texture/flat color — that's the giant tree's bark, the robot
// eggs, the holy-mountain hall art. A scene qualifies here when the game ships
// <name>_visual.png beside the material PNG telescope's scene maps to, and the
// material PNG's dimensions match telescope's copy (guards basename collisions
// across biomes).
//
//   node tools/gen_visual_overlays.mjs [path-to-data.wak.unpacked]
import { readFileSync, writeFileSync, readdirSync, existsSync, copyFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = dirname(dirname(fileURLToPath(import.meta.url)));
const GAME = process.argv[2]
	?? '/home/vitaminmoo/reverse/noita/noita_Jan_25_2025_15:55:41/data/data.wak.unpacked';
const IMPL = join(GAME, 'biome_impl');
const SCENES = join(repo, 'data', 'pixel_scenes');

// telescope scene dir -> game biome_impl subdirs to try, in order. '' is the
// biome_impl root, where the shared scenes live.
const GAME_DIRS = {
	general: [''],
	rainforest_open: ['rainforest'],
	rainforest_dark: ['rainforest_dark', 'rainforest'],
	// spliced scenes were assembled from numbered tiles by the original
	// exporter; their visuals were spliced the same way and already ship.
	spliced: [],
	sky_islands: ['sky_islands'],
};

function pngSize(path) {
	const b = readFileSync(path);
	// IHDR width/height at fixed offsets in any valid PNG
	return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}

const manifest = [];
let copied = 0;
for (const dir of readdirSync(SCENES).sort()) {
	if (!statSync(join(SCENES, dir)).isDirectory()) continue;
	const gameDirs = GAME_DIRS[dir] ?? [dir, ''];
	for (const file of readdirSync(join(SCENES, dir)).sort()) {
		if (!file.endsWith('.png') || file.includes('_visual') || file.includes('_background')) continue;
		const name = file.slice(0, -4);
		const dest = join(SCENES, dir, `${name}_visual.png`);
		if (existsSync(dest)) { manifest.push(`${dir}/${name}`); continue; }
		for (const gd of gameDirs) {
			const mat = join(IMPL, gd, `${name}.png`);
			const vis = join(IMPL, gd, `${name}_visual.png`);
			if (!existsSync(mat) || !existsSync(vis)) continue;
			const a = pngSize(mat), b = pngSize(join(SCENES, dir, file));
			if (a.w !== b.w || a.h !== b.h) continue; // different scene sharing the name
			copyFileSync(vis, dest);
			manifest.push(`${dir}/${name}`);
			copied++;
			break;
		}
	}
}

manifest.sort();
const out = `// GENERATED by tools/gen_visual_overlays.mjs -- do not edit.
// Scenes whose data/pixel_scenes/<dir>/<name>_visual.png carries the engine's
// per-pixel cell-color override art (LoadPixelScene's colors file).
export const VISUAL_OVERLAY_SCENES = new Set(${JSON.stringify(manifest, null, '\t')});
`;
writeFileSync(join(repo, 'js', 'pixel_scene_visuals.js'), out);
console.log(`${manifest.length} scenes with visual art (${copied} newly copied); js/pixel_scene_visuals.js written`);
